server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

  gateway:
    routes:
      - id: security-service
        uri: lb://security-service
        predicates:
          - Path=/auth/**
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/products/**
      - id: customer-service
        uri: lb://customer-service
        predicates:
          - Path=/customers/**
      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/orders/**
      - id: payment-service
        uri: lb://payment-service
        predicates:
          - Path=/payments/**



